[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "javascript"] }
auto-format = true

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "npx", args = ["prettier", "--config", ".prettierrc.toml", "--parser", "typescript"] }
file-types = ["tsx", "ts"]
# formatter = { command = 'prettier', args = ["--parser", "typescript"] }

# [[language]]
# name = "tsx"
# formatter = { command = 'prettier', args = ["--stdin-filename", "file.tsx"] }
# auto-format = true

# [language.debugger]
# command = 'node'
# args = ['users/D065023/apps/node/out/src/nodeDebug.js']

[[language]]
name = "rust"
auto-format = true
language-server = { command = "rust-analyzer" }
